### PR TITLE
Add css/js manifest feature; re-enable caching in dev mode.

### PR DESCRIPTION
**Pull request by seven1m**
To use the manifest feature, just add the following to libraries.php:

``` php
Libraries::add('li3_frontender', array(
    // 'compress' => true,
    'manifests' => array(
        'js' => array(
            'main' => array(
                'main.coffee',
                'popup.coffee',
            )
        )
        'css' => array(
            'main' => array(
                'main.less',
                'popup.less',
            )
        )
    )
));
```

To reference the manifest assets in the view, use the list name as a string:

``` php
<?= $this->assets->script('main') ?> 
<?= $this->assets->style('main') ?>
```

### CODE REVIEW

**Comment by joseym** [comment]
This I like. Does it still work as originally designed as well?

An Li3 console script could also be written to precompile manifest assets.

I still think that, in dev mode, assets should be individual rather than compiled.

**Comment by joseym** [comment]
@seven1m can you update the readme to reflect the new manifest option?

**Comment by seven1m** [comment]
Yes, your plugin still works the way it did before. You can pass a string or an array of filenames to the helper.

I'll update the readme.

**Comment by seven1m** [comment]
OK, I've update the readme -- included in this pull request!

**Pull request merged**
